apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker-service

  template:
    metadata:
      labels:
        app: worker-service

    spec:
      containers:
        - name: worker-service
          image: aswinrj/worker-service

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: worker-service-secret
                  key: slack-bot-token

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3