apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-service
  labels:
    app: worker-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker-service

  template:
    metadata:
      labels:
        app: worker-service

    spec:
      containers:
        - name: worker-service
          image: aswinrj/worker-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

          envFrom:
            - configMapRef:
                name: worker-service-config

            - secretRef:
                name: worker-service-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

          securityContext:
            allowPrivilegeEscalation: false