apiVersion: v1
kind: Secret

metadata:
  name: worker-service-secret

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres

  SLACK_BOT_TOKEN: "xoxb-11586203669683-11596235653588-VOY0QB2dW0TrZVyuNHTPfXHL"