version: '3.8'

services:
  discovery-service:
    image: aswinrj/discovery-service
    container_name: discovery-service
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    image: aswinrj/api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - discovery-service
    ports:
      - "8888:8081"

  auth-service:
    image: aswinrj/auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - db
      - mailpit
      - discovery-service
    ports:
      - "8083:8082"
    volumes:
      - ./database/auth:/app/database/migrations

  db:
    image: postgres:16-alpine
    container_name: flowforge-postgres
    restart: always
    environment:
      POSTGRES_DB: flowforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: flowforge-mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  workflow-service:
    image: anzyl/workflow-service:v1
    container_name: workflow-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - discovery-service
    networks:
      - default
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./database:/app/database

  worker-service:
    build:
      context: .
      dockerfile: worker-service/Dockerfile
    image: flowforge/worker-service:local
    container_name: worker-service
    restart: always
    depends_on:
      - discovery-service
      - kafka
      - db
      - mailpit
    ports:
      - "8084:8084"

  kafka:
    image: apache/kafka:latest
    container_name: flowforge-kafka
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://flowforge-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

volumes:
  postgres_data:
  kafka_data:
