server:
  port: 8083

spring:
  application:
    name: worker-service
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: worker
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: worker
    default-schema: worker
    create-schemas: true


  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}

resilience4j:
  circuitbreaker:
    instances:
      slack:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

      email:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

      http:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

  bulkhead:
    instances:
      slack:
        max-concurrent-calls: 10
        max-wait-duration: 500ms
      email:
        max-concurrent-calls: 10
        max-wait-duration: 500ms
      http:
        max-concurrent-class: 10
        max-wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

  metrics:
    enable:
      all: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
