server:
  port: 8084

spring:
  application:
    name: worker-service

  datasource:
    url: jdbc:postgresql://flowforge-postgres:5432/flowforge
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: worker
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:/app/database/migrations
    schemas: worker
    default-schema: worker
    create-schemas: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: worker-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: mailpit
    port: 1025

slack:
  bot:
    token: {slack-bot-token}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/


