server:
  port: 8888

spring:
  application:
    name: api-gateway
    profiles:
      default: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowedCredentials: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/invitations/**
          filters:
            - JwtAuthFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: workflow-service
          uri: lb://workflow-service
          predicates:
            - Path=/api/v1/executions/**,/api/v1/workflows/**
          filters:
            - JwtAuthFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                key-resolver: "#{@userKeyResolver}"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
app:
  jwt:
    secret: dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWZsb3dmb3JnZS1hdXRoLXNlcnZpY2U=

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted

  metrics:
    enable:
      all: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
