apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DB_URL: jdbc:postgresql://postgres:5432/flowforge

  FLYWAY_LOCATIONS: filesystem:/app/database/migrations/auth

  MAIL_HOST: mailpit
  MAIL_PORT: "1025"

  EUREKA_URL: http://discovery-service:8761/eureka/

  JAEGER_ENDPOINT: http://jaeger:4318/v1/traces

  APP_BASE_URL: https://flowforge.com
