apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWZsb3dmb3JnZS1hdXRoLXNlcnZpY2U=