apiVersion: apps/v1
kind: Deployment

metadata:
  name: discovery-service
  labels:
    app: discovery-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-service

  template:
    metadata:
      labels:
        app: discovery-service

    spec:
      containers:
        - name: discovery-service
          image: aswinrj/discovery-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8761

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          envFrom:
            - configMapRef:
                name: discovery-config

      restartPolicy: Always