spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/flowforge
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.kafka.bootstrap-servers=localhost:29092
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.flyway.locations=filesystem:./database/migrations/workflow
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces