spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://db:5432/flowforge
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.kafka.bootstrap-servers=kafka:9092
spring.flyway.locations=filesystem:/app/database/migrations/workflow
# Eureka Client
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces