spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

eureka.client.service-url.defaultZone=${EUREKA_URL}

management.otlp.tracing.endpoint=${JAEGER_ENDPOINT}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.locations=filesystem:/app/database/migrations/workflow