spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://flowforge-postgres:5432/flowforge
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver