pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Code checked out!'
            }
        }

        stage('Build') {
            steps {
                dir('auth-service') {
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('auth-service') {
                    bat 'docker build -t flowforge-auth:latest .'
                }
            }
        }

    }

    post {
        success {
            echo 'Docker image created successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}