server:
  port: 8081

spring:
  application:
    name: auth-service

  profiles:
    default: dev

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: auth

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: auth
    default-schema: auth
    create-schemas: true

app:
  base-url: ${APP_BASE_URL:http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  metrics:
    enable:
      all: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0

