apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowforge-mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowforge-mailpit
  template:
    metadata:
      labels:
        app: flowforge-mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          ports:
            - containerPort: 1025
            - containerPort: 8025