apiVersion: apps/v1
kind: Deployment

metadata:
  name: workflow-service
  labels:
    app: workflow-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: workflow-service

  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      containers:
        - name: workflow-service
          image: anzyl/workflow-service:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: workflow-config
            - secretRef:
                name: workflow-secret



