apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: DB_URL
              value: jdbc:postgresql://db:5432/flowforge
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
      restartPolicy: Always
      